### ISSUE TITLE
Support Bundle concat code should be consistent with Preflight concat code

### ISSUE THREAD

**Issue by diamonwiggins** [replicatedhq/troubleshoot#1001]
**Describe the rationale for the suggested feature.**

A recent bug was discovered in the concat code of Preflight - https://github.com/replicatedhq/troubleshoot/pull/998. Although there isn't a known issue in the support bundle code, we should update it for consistency.

https://github.com/replicatedhq/troubleshoot/blob/main/pkg/supportbundle/supportbundle.go#L237
https://github.com/replicatedhq/troubleshoot/blob/main/cmd/troubleshoot/cli/run.go#L101-L105

**Describe the feature**
Refactor the Support Bundle Concat logic to be consistent with the changes in #998 

**Describe alternatives you've considered**

Describe alternative solutions here. Include any workarounds you've considered.

**Additional context**

Add additional context about the feature request.  If the change is substantial, consider attaching files to the issue  outlining architectural changes, data flows, file formats etc., anything that helps describe the requested change.

**Comment by yangmeilly** [comment]
this issue has been annihilated by https://github.com/replicatedhq/troubleshoot/pull/1002

**Comment by xavpaice** [comment]
#933 should resolve this as various parts of the codebase are consolidated.  The main issue here is about duplicating the concat code between both `preflight` and `support-bundle`, but that duplication sits in many places in the codebase.

I'll close this since we have #1002 handling the specific issue, and #933 to tidy up in general.
