### ISSUE TITLE
'run-pod' collector should print the name of the failing run

### ISSUE THREAD

**Issue by adamancini** [replicatedhq/troubleshoot#1361]
**Describe the rationale for the suggested feature.**

When a `run-pod` collector fails, such as when the dependent image does not pull, the error printed to the console does not state which collector name is failing;  in a large spec, such as during a support call, or when concatenating multiple specs, it can be difficult to determine which collector fails until you unpack the bundle.

**Describe the feature**

`run-pod` collector (probably _all_ collectors) should print the name of the collector that fails.

**Comment by xavpaice** [comment]
After much discussion:

* The name that is specified in the error message is determined at https://github.com/replicatedhq/troubleshoot/blob/55608c12ede9597fa4106a0bd3228946067cd5ea/pkg/collect/collector.go#L136 - by default, this is the `collectorName`.  If that isn't specified, it's the name of the collector itself.
* the `name:` parameter in a particular collector appears to have little to no effect, and is not documented, but is used in several examples and default specs we ship.  It is also present in different contexts throughout the spec and should be avoided unless it is specifically meaningful for that collector.  For `run-pod`, it is not.
* the `collectorName` is used to determine the output path, and we cannot/should not alter that value because analyzers rely on it.

**NOTE: the `runPod` collector does use `name` to name it's pod - it is important that we maintain this usage!**

Given all this:
* making the `getCollectorName()` function return the content of `name:` if `collectorName` is null was discussed, however we agree that this is ugly and introduces tech debt.
* We should review where we use `name:` in our default specs and examples, and change that to use `collectorName:` if appropriate (updating the associated analyzer also)

New definition of done:
* The following specs have been updated to use `collectorName` where appropriate instead of `name`:
  * https://github.com/replicatedhq/kots/blob/main/pkg/supportbundle/defaultspec/spec.yaml
  * https://github.com/replicatedhq/troubleshoot-specs/blob/main/in-cluster/default.yaml
* All the examples in the [docs](https://troubleshoot.sh/docs) have been through the same review and updated if needed

**Comment by xavpaice** [comment]
This collector shows the `collectorName` field.  We've updated the docs and examples.
