### ISSUE TITLE
HTTP Collector Documentation Confusing

### ISSUE THREAD

**Issue by kireledan** [replicatedhq/troubleshoot#371]
After reviewing the HTTP Collector docs @ https://troubleshoot.sh/docs/collect/http/ , the page mentions that the collector can run inside a container.

> "The http collector can be used to execute http requests from inside the cluster. "

 However, after trying to test this on a personal cluster, I found that its unable to hit endpoints that a cluster can reach. It is able to hit local endpoints on my machine though. 

Is there an undocumented flag for getting the HTTP request to run in the targeted cluster? Or is this just mis-worded / a planned feature.

**Comment by adamancini** [comment]
@kireledan I'll take a look, but can you share your test procedure showing how the HTTP collector failed in your case?

**Comment by adamancini** [comment]
@kireledan The intent is that the http request does originate from a pod inside the cluster, so if it's not working for you I'd like to understand how that failed & if there's a bug

**Comment by adamancini** [comment]
taking a look at the code, the collector doesn't run inside a container, but executed by the `support-bundle` or `preflight` binaries, so I can see how it would fail to resolve outside the cluster - after talking with some of the engineers at Replicated this might not be the only collector that acts that way.  I'll take a look for any more.  

I think we should probably fix that so that the collectors default to run inside the cluster, and we should consider having a client-side run as an option so the collectors can cover both use cases.

**Comment by xavpaice** [comment]
I'm going to close this to consolidate the work in #1145
