### ISSUE TITLE
MySQL Collector and Analyzer support checking for MySQL properties

### ISSUE THREAD

**Issue by rocktavious** [replicatedhq/troubleshoot#555]
We have a business requirement that we need to run a preflight check to make sure a MySQL DB our app connects to has these parameters set

```
"character_set_server" = "utf8mb4"
"collation_server" = "utf8mb4_unicode_ci"
"init_connect" = "SET collation_connection = utf8mb4_unicode_ci,NAMES utf8mb4"
"innodb_file_format" = "Barracuda"
"innodb_large_prefix" = "1"
"innodb_strict_mode" = "1"
"log_bin_trust_function_creators" = "1"
```

It seems like we could adjust the https://github.com/replicatedhq/troubleshoot/blob/main/pkg/collect/mysql.go to run an addtional query when configured of `SHOW VARIABLES` that it then stuffs in the json.

Then we could adjust the https://github.com/replicatedhq/troubleshoot/blob/main/pkg/analyze/mysql.go to be given a list of expected "key" == "value" stanza's which it could run through and ensure they all match or fail.

There probably some more to it but at first glance it seems quite easy to implement.  Would love any feedback - we are keen to have this so we could dedicate an engineer to implement this.

**Comment by OGtrilliams** [comment]
Hello @rocktavious ! Thanks for reaching out. The issue has been added to the troubleshoot.sh [community agenda](https://hackmd.io/yZbotEHdTg6TfRZBzb8Tcg) for discussion. If you're available, it would be wonderful if you could join us so that we can discuss your goals & develop a plan to implement the desired changes. We will be meeting at 11AM PST on this Zoom link: https://replicated.zoom.us/j/83977996608?pwd=SmNobzF4V0puUTA5a0xZb1prdmthZz09

**Comment by eochoa260** [comment]
Hi @OGtrilliams! @rocktavious is tentative for the meeting but I will be able to attend in his place to discuss if he's not able to make it.

**Comment by emosbaugh** [comment]
We would welcome the contribution!

Capturing a discussion we had in the troubleshoot community meeting.

Adding additional data to the mysql collector makes sense.

Rather than reusing the mysql analyzer it may be best to use the text analyzer or adding a new key value analyzer.

It may make sense to add proposed spec changes here before implementation.

Thanks!

**Comment by rocktavious** [comment]
The PR has been merged and we've tested it works correctly for our usecase.  Thanks everyone.
