### ISSUE TITLE
Add capability to run linters and commit hooks to the projects development flow

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/troubleshoot#754]
### Problem to solve

Perform quality gating checks on the developers machine before committing code into version control.

### Customer impact

Potentially reduce bugs in the software by catching lint errors earlier

### Developer experience impact
- Git pre-commit hooks will help detect and (optionally) autofix various issues (lint, formatting etc) before committing code
- Initially, it will take time to get used to the workflow for developers who have not used pre-commit hooks in their workflow. This can be a barrier to entry for people willing to make contributions. We can settle with making `pre-commit` optional to mitigate this.
- Initial runs of the linters and pre-commit hooks will expose many changes which will require time commitment to resolve.

### Proposed solution

Add the following two tools that will be run on developer machine.

- [golangci-lint ](https://golangci-lint.run/)- a tool that bundles [many well known linters](https://golangci-lint.run/usage/linters/) into a single binary. It also provides an [easy configuration mechanism](https://golangci-lint.run/usage/configuration/) where a project can select a few linters and pass in options that best work for the project. The defaults given should be sufficient for this project.
- [pre-commit](https://pre-commit.com/) - a tool that injects a [git pre-commit hook](https://git-scm.com/docs/githooks#_pre_commit) that gets run whenever someone commits changes. There are a many [pre-commit plugins](https://pre-commit.com/hooks.html) to pick from.

**Comment by xavpaice** [comment]
Make targets have been merged, next steps is to decide on whether pre-commit hooks are appropriate for the Troubleshoot project.

@adamancini would appreciate your thoughts on this.

**Comment by chris-sanders** [comment]
In general my issue with pre-commit is that it relies on a user having dependencies installed and configured before they commit. I've seen in the past people being told they have to uncommit and recommit changes to try and re-run tests. I don't see any reason anyone should have to make a commit just to trigger or re-trigger testing. 

Overall I just think pre-commit violates the fundamentals of what source control management should be doing. Test should be easy to run and commits should not in any way imply fully functional and working code. For people to collaborate we should encourage committing code that isn't yet done and working in the open, and testing at that stage shouldn't necessarily be passing at which point you expect pre-commit to fail and it has no value anymore (running expected failures in testing is of little use).

The best use case I've seen for pre-commit has been to relegate it to linting and code formatting. With modern LSP implementations these can be done _live_ in the editor and applied (if you like) on save rather than commit. This accomplishes the same thing but can be done in real-time and allows developers to define their preference for when and how lint runs.
